import { createClient } from "@supabase/supabase-js";
import PlaidConnect from "./components/PlaidConnect";
import { DashboardAccount, InvestmentHolding, InvestmentSnapshot, RecentTransaction, rewardBalances } from "../lib/dashboard";
import { DASHBOARD_TARGETS, buildDashboardViewModel } from "../lib/dashboardViewModel";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);
const FIXED_USER_ID = "4ac12929-b795-474e-9001-56190c6c4daf";

function number(value: number | string | null | undefined) { const parsed = Number(value); return value == null || value === "" || !Number.isFinite(parsed) ? null : parsed; }
function money(value: number | string | null | undefined) { const amount = number(value); return amount == null ? "Unavailable" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(amount); }
function percent(value: number | null | undefined) { return value == null ? "Unavailable" : `${value >= 0 ? "+" : ""}${value.toFixed(1)}%`; }
function name(account: DashboardAccount) { return `${account.institution_name ?? "Unknown institution"} · ${account.account_name ?? "Unnamed account"}${account.mask ? ` ••••${account.mask}` : ""}`; }
function category(tx: RecentTransaction) { return Array.isArray(tx.category) ? tx.category.join(" > ") : tx.category ?? "Uncategorized"; }

function Card({ label, value, detail, dark, danger }: { label: string; value: string; detail?: string; dark?: boolean; danger?: boolean }) {
  const style = dark ? "border-slate-950 bg-slate-950 text-white" : danger ? "border-rose-100 bg-rose-50" : "border-slate-200 bg-white";
  return <div className={`rounded-2xl border p-5 shadow-sm ${style}`}><p className={`text-xs font-semibold uppercase tracking-[.16em] ${dark ? "text-slate-300" : "text-slate-500"}`}>{label}</p><p className="mt-3 text-3xl font-semibold tracking-tight">{value}</p>{detail && <p className={`mt-2 text-sm ${dark ? "text-slate-300" : "text-slate-500"}`}>{detail}</p>}</div>;
}
function Header({ eyebrow, title, detail }: { eyebrow: string; title: string; detail?: string }) { return <div><p className="text-xs font-semibold uppercase tracking-[.16em] text-emerald-700">{eyebrow}</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">{title}</h2>{detail && <p className="mt-1 text-sm text-slate-500">{detail}</p>}</div>; }
function Empty({ children }: { children: React.ReactNode }) { return <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4 text-sm text-slate-500">{children}</div>; }

export default async function Home() {
  const now = new Date();
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().slice(0, 10);
  const monthEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString().slice(0, 10);
  const historyStart = new Date(now.getFullYear(), now.getMonth() - 5, 1).toISOString().slice(0, 10);
  const [accountsResult, monthResult, historyResult, recentResult, holdingsResult, snapshotsResult] = await Promise.all([
    supabase.from("accounts").select("id, institution_name, account_name, mask, account_type, account_subtype, current_balance, available_balance, plaid_account_id, plaid_item_id").eq("user_id", FIXED_USER_ID).order("created_at", { ascending: false }),
    supabase.from("transactions").select("id, date, name, merchant_name, amount, category, pending, plaid_transaction_id, account_id").eq("user_id", FIXED_USER_ID).gte("date", monthStart).lte("date", monthEnd).order("date", { ascending: false }),
    supabase.from("transactions").select("id, date, name, merchant_name, amount, category, pending, plaid_transaction_id, account_id").eq("user_id", FIXED_USER_ID).gte("date", historyStart).lte("date", monthEnd).order("date", { ascending: false }),
    supabase.from("transactions").select("id, date, name, merchant_name, amount, category, pending, plaid_transaction_id, account_id").eq("user_id", FIXED_USER_ID).order("date", { ascending: false }).limit(15),
    supabase.from("investment_holdings").select("id, plaid_account_id, security_id, ticker_symbol, security_name, quantity, institution_price, institution_value, cost_basis").eq("user_id", FIXED_USER_ID).order("institution_value", { ascending: false }),
    supabase.from("investment_snapshots").select("id, plaid_item_id, plaid_account_id, snapshot_date, portfolio_value, created_at").eq("user_id", FIXED_USER_ID).order("snapshot_date", { ascending: false }),
  ]);
  const accounts = (accountsResult.data ?? []) as DashboardAccount[];
  const recent = (recentResult.data ?? []) as RecentTransaction[];
  const holdings = (holdingsResult.data ?? []) as InvestmentHolding[];
  const snapshots = (snapshotsResult.data ?? []) as InvestmentSnapshot[];
  const view = buildDashboardViewModel({ accounts, monthTransactions: (monthResult.data ?? []) as RecentTransaction[], historicalTransactions: (historyResult.data ?? []) as RecentTransaction[], holdings, snapshots, now });
  const monthName = new Intl.DateTimeFormat("en-US", { month: "long" }).format(now);
  const dataUnavailable = Boolean(accountsResult.error || monthResult.error || historyResult.error || recentResult.error || holdingsResult.error || snapshotsResult.error);
  const debt = Math.abs(view.accountSummary.credit);
  const availableCredit = view.creditAccounts.reduce((sum, account) => sum + (number(account.available_balance) ?? 0), 0);
  const utilization = debt + availableCredit > 0 ? debt / (debt + availableCredit) * 100 : null;
  const chartMax = Math.max(...view.monthlyHistory.flatMap((item) => [item.income, item.spending]), 1);
  const iraAccounts = view.retirementAccounts.filter((account) => account.account_subtype?.toLowerCase().includes("ira"));
  const k401Accounts = view.retirementAccounts.filter((account) => account.account_subtype?.toLowerCase().includes("401"));

  return <main className="min-h-screen bg-slate-50 text-slate-950"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8">
    <header className="flex flex-wrap items-start justify-between gap-5 border-b border-slate-200 pb-7"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-emerald-700">Personal financial operating system</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Budget Builder</h1><p className="mt-2 text-sm text-slate-500">Your current position, cash flow, and progress in one place.</p></div><PlaidConnect investmentPlaidItemId={accounts.find((account) => account.account_type?.toLowerCase() === "investment")?.plaid_item_id} /></header>
    {dataUnavailable && <div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Some financial data is unavailable. Connected data will appear when its source can be loaded.</div>}

    <section className="mt-8"><Header eyebrow="Financial Snapshot" title="Your position right now" detail="Transfers and credit-card payments remain separate from spending." /><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card label="Net Worth" value={money(view.accountSummary.netWorth)} detail="Current connected balances" dark /><Card label="Cash" value={money(view.accountSummary.cash)} detail={`${view.cashAccounts.length} cash accounts`} /><Card label="Investments" value={money(view.accountSummary.investments)} detail={`${view.taxableInvestmentAccounts.length} taxable accounts`} /><Card label="Debt" value={money(debt)} detail={`${view.creditAccounts.length} credit accounts`} danger /></div><div className="mt-4 grid grid-cols-2 gap-3 border-y border-slate-200 py-4 md:grid-cols-5">{[["Net worth change", "Unavailable"], ["Monthly income", money(view.monthly.income)], ["Monthly spending", money(view.monthly.spending)], ["Net cash flow", money(view.netCashFlow)], ["Savings rate", percent(view.savingsRate)]].map(([label, value]) => <div key={label}><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>)}</div></section>

    <section className="mt-12"><Header eyebrow="Cash Flow" title={`${monthName} income and spending`} /><div className="mt-5 grid gap-5 lg:grid-cols-5"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-3"><div className="flex justify-between"><div><h3 className="font-semibold">Income vs. spending</h3><p className="mt-1 text-sm text-slate-500">Six-month history from normalized transactions.</p></div><p className="text-xs text-slate-500">Monthly</p></div><div className="mt-8 flex h-48 items-end gap-3">{view.monthlyHistory.map((item) => <div key={item.label} className="flex flex-1 flex-col items-center gap-2"><div className="flex h-40 items-end gap-1"><i className="w-2 rounded-t bg-emerald-500" style={{ height: `${Math.max(item.income / chartMax * 100, item.income ? 4 : 0)}%` }} /><i className="w-2 rounded-t bg-slate-900" style={{ height: `${Math.max(item.spending / chartMax * 100, item.spending ? 4 : 0)}%` }} /></div><span className="text-xs text-slate-500">{item.label}</span></div>)}</div><p className="mt-4 text-xs text-slate-500"><span className="mr-4 text-emerald-600">● Income</span><span className="text-slate-900">● Spending</span></p></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2"><h3 className="font-semibold">Monthly plan</h3><div className="mt-5 space-y-5"><div className="flex justify-between text-sm"><span className="text-slate-500">Income</span><span className="font-semibold">{money(view.monthly.income)}</span></div><div><div className="flex justify-between text-sm"><span className="text-slate-500">Net spending</span><span className="font-semibold">{money(view.monthly.spending)}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-emerald-500 via-amber-400 to-rose-600" style={{ width: `${Math.min(view.spendingBudgetUsage, 100)}%` }} /></div><p className="mt-2 text-xs text-slate-500">{view.spendingBudgetUsage.toFixed(0)}% of {money(DASHBOARD_TARGETS.monthlySpendingGoal)} goal</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Net cash flow</p><p className="mt-1 text-2xl font-semibold">{money(view.netCashFlow)}</p></div></div></div></div></section>

    <section className="mt-12"><Header eyebrow="Investments" title="Portfolio and performance" detail="Gains and losses change net worth through connected investment balances." /><div className="mt-5 grid gap-4 lg:grid-cols-4"><Card label="Investment assets" value={money(view.accountSummary.investments)} /><Card label="Total return" value={money(view.investmentPerformance.totalReturn)} detail={percent(view.investmentPerformance.totalReturnPercent)} /><Card label="YTD return" value="Unavailable" detail="Needs a compatible Jan. 1 snapshot" /><Card label="7-day return" value={money(view.investmentPerformance.sevenDayReturn)} detail={percent(view.investmentPerformance.sevenDayReturnPercent)} /></div><div className="mt-5 grid gap-5 lg:grid-cols-5"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-3"><h3 className="font-semibold">Holdings</h3><div className="mt-4 divide-y divide-slate-100">{holdings.length === 0 ? <Empty>No investment holdings are connected.</Empty> : holdings.map((holding) => { const value = number(holding.institution_value); const cost = number(holding.cost_basis); const gain = value != null && cost != null ? value - cost : null; const gainPercent = gain != null && cost ? gain / cost * 100 : null; return <div key={holding.id} className="grid gap-3 py-4 sm:grid-cols-[1fr_auto_auto]"><div><p className="font-medium">{holding.security_name ?? "Unknown security"}</p><p className="mt-1 text-sm text-slate-500">{holding.ticker_symbol ?? "—"} · {holding.quantity == null ? "Shares unavailable" : `${holding.quantity} shares`}</p></div><div className="sm:text-right"><p className="text-xs text-slate-500">Current value</p><p className="font-semibold">{money(value)}</p></div><div className="sm:text-right"><p className="text-xs text-slate-500">Gain/loss</p><p className={gain == null ? "font-semibold text-slate-500" : gain >= 0 ? "font-semibold text-emerald-700" : "font-semibold text-rose-700"}>{gain == null ? "Unavailable" : `${money(gain)} · ${percent(gainPercent)}`}</p></div></div>; })}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2"><h3 className="font-semibold">Portfolio history</h3><div className="mt-4 space-y-2">{snapshots.length === 0 ? <Empty>Portfolio history unavailable until snapshots are recorded.</Empty> : snapshots.slice(0, 6).map((snapshot) => <div key={snapshot.id} className="flex justify-between rounded-xl bg-slate-50 p-3 text-sm"><span className="text-slate-500">{snapshot.snapshot_date}</span><span className="font-semibold">{money(snapshot.portfolio_value)}</span></div>)}</div><h3 className="mt-7 font-semibold">Allocation</h3><p className="mt-2 text-sm text-slate-500">Unavailable — connected holdings do not include reliable asset-class metadata.</p></div></div></section>

    <section className="mt-12"><Header eyebrow="Retirement" title="Long-term accounts" detail="Retirement classification uses Plaid account metadata, not institution names." /><div className="mt-5 grid gap-5 lg:grid-cols-3"><Card label="Retirement assets" value={money(view.retirementAssets)} detail={`${view.retirementAccounts.length} connected accounts`} /><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="font-semibold">Roth IRA</h3>{iraAccounts.length === 0 ? <div className="mt-4"><Empty>Not connected or not distinguishable from current account metadata.</Empty></div> : iraAccounts.map((account) => <div key={account.id} className="mt-4"><p className="text-sm text-slate-500">{name(account)}</p><p className="mt-1 text-xl font-semibold">{money(account.current_balance)}</p><p className="mt-1 text-xs text-slate-500">Contributions and match: Unavailable</p></div>)}</div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="font-semibold">401(k)</h3>{k401Accounts.length === 0 ? <div className="mt-4"><Empty>Not connected or not distinguishable from current account metadata.</Empty></div> : k401Accounts.map((account) => <div key={account.id} className="mt-4"><p className="text-sm text-slate-500">{name(account)}</p><p className="mt-1 text-xl font-semibold">{money(account.current_balance)}</p><p className="mt-1 text-xs text-slate-500">Contributions and match: Unavailable</p></div>)}</div></div></section>

    <section className="mt-12 grid gap-8 xl:grid-cols-2"><div><Header eyebrow="Cash" title="Liquidity by account" /><div className="mt-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">{view.cashAccounts.length === 0 ? <Empty>No depository accounts are connected.</Empty> : <div className="divide-y divide-slate-100">{view.cashAccounts.map((account) => <div key={account.id} className="flex justify-between gap-4 py-4 first:pt-0 last:pb-0"><div><p className="font-medium">{name(account)}</p><p className="mt-1 text-sm text-slate-500">{account.available_balance == null ? "Available balance unavailable" : `Available ${money(account.available_balance)}`}</p></div><p className="font-semibold">{money(account.current_balance)}</p></div>)}</div>}<div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="font-medium">Cash earning interest</p><p className="mt-1 text-sm text-slate-500">Unavailable — no APY data source is connected.</p></div></div></div><div><Header eyebrow="Credit & Debt" title="Balances and available credit" /><div className="mt-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid grid-cols-2 gap-4"><div><p className="text-xs text-slate-500">Total owed</p><p className="mt-1 text-2xl font-semibold">{money(debt)}</p></div><div><p className="text-xs text-slate-500">Utilization</p><p className="mt-1 text-2xl font-semibold">{percent(utilization)}</p></div></div><div className="mt-5 divide-y divide-slate-100">{view.creditAccounts.length === 0 ? <Empty>No credit accounts are connected.</Empty> : view.creditAccounts.map((account) => <div key={account.id} className="flex justify-between gap-4 py-4"><div><p className="font-medium">{name(account)}</p><p className="mt-1 text-sm text-slate-500">{account.available_balance == null ? "Available credit unavailable" : `Available ${money(account.available_balance)}`}</p><p className="mt-1 text-xs text-slate-500">Statement balance and due date: Unavailable</p></div><p className="font-semibold">{money(Math.abs(number(account.current_balance) ?? 0))}</p></div>)}</div></div></div></section>

    <section className="mt-12"><Header eyebrow="Spending" title={`${monthName} spending`} /><div className="mt-5 grid gap-5 lg:grid-cols-5"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2"><p className="text-sm text-slate-500">Net personal spending</p><p className="mt-2 text-4xl font-semibold">{money(view.monthly.spending)}</p><p className="mt-2 text-sm text-slate-500">Goal: {money(DASHBOARD_TARGETS.monthlySpendingGoal)} · {view.spendingBudgetUsage.toFixed(0)}% used</p><div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-emerald-500 via-amber-400 to-rose-600" style={{ width: `${Math.min(view.spendingBudgetUsage, 100)}%` }} /></div><div className="mt-6 grid grid-cols-2 gap-4"><div><p className="text-xs text-slate-500">Gross spending</p><p className="mt-1 font-semibold">{money(view.monthly.grossSpending)}</p></div><div><p className="text-xs text-slate-500">Projected month-end</p><p className="mt-1 font-semibold">{money(view.projectedMonthEndSpending)}</p></div></div></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-3"><h3 className="font-semibold">Category breakdown</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{view.budgetLines.map((line) => <div key={line.label} className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{line.label}</p><p className="mt-2 text-xl font-semibold">{money(line.total)}</p></div>)}<div className="rounded-xl border border-dashed border-slate-300 p-4"><p className="text-xs text-slate-500">Other</p><p className="mt-2 text-sm text-slate-500">Included with Shopping & Personal when uncategorized.</p></div></div></div></div></section>

    <section className="mt-12"><Header eyebrow="Financial Goals" title="Goals, when you are ready" detail="Goal progress will appear from a supported goal data source." /><div className="mt-5"><Empty>No financial goals have been configured. Emergency fund, Roth IRA, 401(k), travel, savings, and custom goals can appear here when data is connected.</Empty></div></section>
    <section className="mt-12 grid gap-8 xl:grid-cols-3"><div className="xl:col-span-2"><Header eyebrow="Recent Activity" title="Latest transactions" /><div className="mt-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">{recent.length === 0 ? <Empty>No recent transactions available.</Empty> : <div className="divide-y divide-slate-100">{recent.map((tx) => { const amount = number(tx.amount); const transfer = category(tx).toLowerCase().includes("transfer"); return <div key={tx.id} className="flex justify-between gap-4 py-4 first:pt-0 last:pb-0"><div className="min-w-0"><p className="truncate font-medium">{tx.merchant_name ?? tx.name ?? "Unknown transaction"}</p><p className="mt-1 text-sm text-slate-500">{tx.date} · {category(tx)} {transfer ? "· Transfer" : ""}{tx.pending ? " · Pending" : ""}</p></div><p className={amount != null && amount < 0 ? "font-semibold text-emerald-700" : "font-semibold"}>{money(amount)}</p></div>; })}</div>}</div></div><div><Header eyebrow="Rewards" title="Program balances" /><div className="mt-5 space-y-3">{rewardBalances.map((reward) => <div key={reward.label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="font-medium">{reward.label}</p><p className="mt-2 text-sm text-slate-500">{reward.value == null ? "Balance unavailable" : reward.value}</p></div>)}</div></div></section>
    <section className="mt-12 rounded-2xl border border-indigo-100 bg-indigo-50 p-7"><p className="text-xs font-semibold uppercase tracking-[.16em] text-indigo-700">Future AI</p><h2 className="mt-2 text-2xl font-semibold">Richard&apos;s Briefing</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-indigo-950/70">Richard&apos;s daily financial briefing will appear here once AI analysis is connected. It will receive normalized summaries of your position, cash flow, investments, goals, and major activity—not raw Plaid credentials.</p><p className="mt-5 inline-flex rounded-full border border-indigo-200 bg-white px-3 py-1 text-xs font-medium text-indigo-700">AI analysis not connected</p></section>
    <section className="mt-12 border-t border-slate-200 pt-8"><Header eyebrow="Connected Accounts" title="Account management" detail="Refresh or connect accounts without leaving your financial overview." /><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{view.accounts.length === 0 ? <Empty>No connected accounts yet.</Empty> : view.accounts.map((account) => <div key={account.id} className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-500">{account.accountClass}</p><p className="mt-2 font-semibold">{name(account)}</p><p className="mt-4 text-xs text-slate-500">Current balance</p><p className="mt-1 text-xl font-semibold">{money(account.current_balance)}</p></div>)}</div></section>
  </div></main>;
}
